### PR TITLE
Add instrumentation for functions 8 and 9

### PR DESCRIPTION
**Pull request by adambenali**
Instrumentation of `KdTree::searchNode` and `SuffixTree.TreePrinter::getString`

### CODE REVIEW

**Review by ChangGabriel — CHANGES_REQUESTED** [review]
Looks good but merge conflict needs to be fixed first :)

**Review by jrutqvist — APPROVED** [review]
Looks good!

**Comment by jrutqvist** [comment]
Still can't merge the PR though, does @ChangGabriel need to approve the changes?

**Review by adambenali — COMMENTED** [review]
The conflict is solved, so yeah it seems like Gabriel needs to approve something.

**Review by ChangGabriel — APPROVED** [review]
Looks good, Sorry that I didnt look earlier.

**Pull request merged**
